# Generated by Django 3.1.2 on 2020-11-02 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('usn', models.CharField(max_length=256, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('branch', models.CharField(blank=True, max_length=256, null=True)),
                ('sem', models.CharField(blank=True, max_length=256, null=True)),
                ('course1', models.CharField(max_length=256, null=True)),
                ('course2', models.CharField(max_length=256, null=True)),
                ('course3', models.CharField(max_length=256, null=True)),
                ('course4', models.CharField(max_length=256, null=True)),
                ('course5', models.CharField(blank=True, max_length=256, null=True)),
                ('course6', models.CharField(blank=True, max_length=256, null=True)),
                ('course7', models.CharField(blank=True, max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('sem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.semester')),
            ],
        ),
    ]
