# Generated by Django 3.1.2 on 2020-11-04 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20201104_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=256, null=True)),
                ('github', models.CharField(blank=True, max_length=256, null=True)),
                ('linked', models.CharField(blank=True, max_length=256, null=True)),
                ('bio', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
