# Generated by Django 3.1.2 on 2020-11-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='avatar',
            field=models.CharField(blank=True, default='dist/img/avatar5.png', max_length=20, null=True),
        ),
    ]
