# Generated by Django 3.1.1 on 2020-10-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='username',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
