# Generated by Django 3.1.1 on 2020-10-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20201016_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='username',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
