# Generated by Django 3.1.1 on 2020-10-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_auto_20201017_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
